server:
  port: 8001

spring:
  application:
    name: logging-service
  elasticsearch:
    uris: https://a1b08b0a2246456f8f8b97d3de898922.us-central1.gcp.cloud.es.io:9243
    username: elastic
    password: dXhIw40iCad33fKzytgpEwKU